baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'sandbox'

[[menu.main]]
  name = "A propos"
  url = "/about"

[[menu.main]]
  name = "Blog"
  url = "/blog"
  
[[menu.social]]
name = "GitHub"
url = "https://github.com/VotreCompteGithub"
pre = "<i class='fab fa-github'></i>"

[[menu.social]]
name = "Twitter"
url = "https://twitter.com/VotreCompteTwitter"
pre = "<i class='fab fa-twitter'></i>"

[[menu.footer]]
name = "A propos"
url = "/about"

[[menu.footer]]
name = "Protection des données"
url = "/protection-des-donnees"
